name: Test Cancel Run - STG

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run to Cancel'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  orchestration:
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.run.outputs.tasks }}
      run_id: ${{ steps.run.outputs.run_id }}
    steps:
      - uses: stack-spot/runtime-manager-action@stg
        id: run
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
          WORKSPACE: Runtimes
          ENVIRONMENT: production
          VERSION_TAG: ${{ github.sha }}
          TF_STATE_BUCKET_NAME: test
          TF_STATE_REGION: test
          IAC_BUCKET_NAME: test
          IAC_REGION: test
          VERBOSE: true
      - name: Check Run Tasks Data
        run: echo "Tasks = ${{ steps.run.outputs.tasks }}"
        shell: bash
  cancel-run:
    runs-on: ubuntu-latest
    needs: [orchestration]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: Cancel run
        uses: stack-spot/runtime-cancel-run-action@stg
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
          RUN_ID: ${{ needs.orchestration.outputs.run_id }}